### ISSUE TITLE
IH {small|medium|large} images background, set to transparent

### ISSUE THREAD

**Issue by lat9** [lat9/zen_Image-Handler#17]
See [this](https://www.zen-cart.com/showthread.php?222983-Image-Handler-5-(for-v1-5-5-v1-5-8)-Support-Thread&p=1402046) Zen Cart support thread.

Updated link for new ZC forum: https://www.zen-cart.com/threads/199527?page=32#post-1336689

It _appears_ that setting those values to `transparent` is resulting in logs similar to
```
Request URI: /index.php?main_page=product_info&cPath=5_6&products_id=425, IP address: 54.36.148.169, Language id 2
#0 /.../htdocs/includes/classes/bmz_image_handler.class.php(1055): zen_debug_error_handler()
#1 /.../htdocs/includes/classes/bmz_image_handler.class.php(856): ih_image->get_background_rgb()
#2 /.../htdocs/includes/classes/bmz_image_handler.class.php(430): ih_image->resize_imageGD()
#3 /.../htdocs/includes/classes/bmz_image_handler.class.php(282): ih_image->get_resized_image()
#4 /.../htdocs/includes/functions/extra_functions/functions_bmz_image_handler.php(154): ih_image->get_local()
#5 /.../htdocs/includes/functions/html_output.php(215): handle_image()
#6 /.../htdocs/includes/templates/bootstrap/templates/tpl_modules_main_product_image.php(19): zen_image()
#7 /.../htdocs/includes/templates/bootstrap/templates/tpl_product_info_display.php(61): require('/data01/virt991...')
#8 /.../htdocs/includes/modules/pages/product_info/main_template_vars.php(140): require('/data01/virt991...')
#9 /.../htdocs/includes/templates/bootstrap/common/tpl_main_page.php(227): require('/data01/virt991...')
#10 /.../htdocs/index.php(94): require('/data01/virt991...')
--> PHP Warning: Undefined array key 1 in /.../htdocs/includes/classes/bmz_image_handler.class.php on line 1055.
```

**Comment by piloujp** [comment]
I am still getting those. A solution was provided in the forum linked above, why it was never applied? Is/was there a plan to do a deeper rewrite?

**Comment by lat9** [comment]
Need to protect against misconfiguration of background (it should be dd:dd:dd). 

<img width="1218" height="913" alt="Image" src="https://github.com/user-attachments/assets/630a650f-7e9e-4f53-87e0-5ae4a920b20f" />

**Comment by torvista** [comment]
Tangentially...to validate database entries, the FILTER_CALLBACK of Instant Search is a solution that does not seem to be commonly used.

https://github.com/zencart/zencart/issues/7477#issuecomment-5646748212
